<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MaterialConfigSeeder extends Seeder
{
    public function run()
    {
        $boqConfigId = 1; // Assuming `boq_configs` table already has an entry with id 1. Adjust as necessary.

        $materialConfigs = [
            [
                'item_code' => 'rods',
                'article_no' => '1000001',
                'hs_code' => '',
                'item_name' => 'Rods',
                'length' => null,
                'no' => 100,
                'weight_per_cm' => 0.000986,
                'unit_price' => 1,
                'specs' => 'Wire round 4mm',
                'common' => 1,
                'boq_config_id' => $boqConfigId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_code' => 'channels',
                'article_no' => '1000002',
                'hs_code' => '',
                'item_name' => 'Channels',
                'length' => '255',
                'no' => null,
                'weight_per_cm' => 0.004706,
                'unit_price' => 1,
                'specs' => 'U Channel 2mm',
                'common' => 1,
                'boq_config_id' => $boqConfigId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_code' => 'poles_on_c',
                'article_no' => '1000003',
                'hs_code' => '',
                'item_name' => 'Poles ( On C)',
                'length' => null,
                'no' => 2,
                'weight_per_cm' => 0.030144,
                'unit_price' => 1,
                'specs' => 'Sq Pipe 2mm 40x60x1600',
                'common' => 1,
                'boq_config_id' => $boqConfigId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_code' => 'base_plate_on_c',
                'article_no' => '1000004',
                'hs_code' => '',
                'item_name' => 'Base Plate (On C)',
                'length' => '100x80x0.6',
                'no' => 2,
                'weight_per_cm' => 0.19,
                'unit_price' => 1,
                'specs' => '6mm',
                'common' => 1,
                'boq_config_id' => $boqConfigId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_code' => 'poles_in_c',
                'article_no' => '1000005',
                'hs_code' => '',
                'item_name' => 'Poles ( In C)',
                'length' => null,
                'no' => 2,
                'weight_per_cm' => 0.030144,
                'unit_price' => 1,
                'specs' => 'Sq Pipe 2mm 40x60x2100',
                'common' => 1,
                'boq_config_id' => $boqConfigId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_code' => 'polecovers',
                'article_no' => '1000006',
                'hs_code' => '',
                'item_name' => 'Polecovers',
                'length' => null,
                'no' => 2,
                'weight_per_cm' => null,
                'unit_price' => 0.25,
                'specs' => '',
                'common' => 1,
                'boq_config_id' => $boqConfigId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_code' => 'brackets',
                'article_no' => '1000007',
                'hs_code' => '',
                'item_name' => 'Brackets',
                'length' => '22x4',
                'no' => null,
                'weight_per_cm' => 0.14,
                'unit_price' => 1,
                'specs' => '2mm',
                'common' => 1,
                'boq_config_id' => $boqConfigId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_code' => 'spacers',
                'article_no' => '1000008',
                'hs_code' => '',
                'item_name' => 'Spacers',
                'length' => null,
                'no' => 32,
                'weight_per_cm' => 0.004706,
                'unit_price' => 1,
                'specs' => '2mm',
                'common' => 1,
                'boq_config_id' => $boqConfigId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_code' => 'carriage_bolts_and_nuts_M6x25',
                'article_no' => '1000009',
                'hs_code' => '',
                'item_name' => 'Carriage Bolts and Nuts M6 x 25',
                'length' => null,
                'no' => null,
                'weight_per_cm' => null,
                'unit_price' => 0.02,
                'specs' => '',
                'common' => 1,
                'boq_config_id' => $boqConfigId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'item_code' => 'bolts_for_brackets_M6x30',
                'article_no' => '1000010',
                'hs_code' => '',
                'item_name' => 'Bolts for Brackets M6 x 30',
                'length' => null,
                'no' => null,
                'weight_per_cm' => null,
                'unit_price' => 0.02,
                'specs' => '',
                'common' => 1,
                'boq_config_id' => $boqConfigId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];


        DB::table('material_configs')->insert($materialConfigs);
    }
}
